### ISSUE TITLE
Cannot switch back to the official dash

### ISSUE THREAD

**Issue by HamzaETTH** [KrisIsBackAU/Oculus-VR-Dash-Manager#6]
I've been using this forever and I recently got an issue that prevent me from switching back to the official dash. I open the tool (1.0.3.0 - 1.0.3.1), click the official dash button and that's when mouse cursor automatically get moved to the center of the tool windows and then it crashes. I've tried running the tool as admin and restarted my pc to no avail. I have a dump made with procdump that is pretty heavy (~450mb) if it's needed.

![video of the behavior in question](https://i.imgur.com/A1l1n28.gif)

Here is the diagnostics windows.
![Oculus_VR_Dash_Manager_YU5VYDLBc2](https://user-images.githubusercontent.com/73552421/227271757-9c91d24a-fcfd-4f49-baed-478e825c8168.png)

**Comment by KrisIsBackAU** [comment]
Odd, any chance of the error that is submitted to event viewer ?
Will add a self logger and try and make it handle that spot better to reveal what happening.
Thanks. Kris.

**Comment by KrisIsBackAU** [comment]
Added logging, give 1.0.3.2 a shot and see what it spits out or doesnt.

**Comment by HamzaETTH** [comment]
Thank you, I decided to debug it and it's seem like I had a remnant OculusDash.exe.delete who was causing the exception. This line:

`File.Move(Software.Oculus.Oculus_Dash_File, $"{Software.Oculus.Oculus_Dash_File}.delete");`

Deleting it manually resolved the problem.
 
[ErrorLog.txt](https://github.com/KrisIsBackAU/Oculus-VR-Dash-Manager/files/11067482/ErrorLog.txt)

**Comment by KrisIsBackAU** [comment]
Yep that is the cause, added in:
if (File.Exists($"{Software.Oculus.Oculus_Dash_File}.delete"))
{
    File.Delete($"{Software.Oculus.Oculus_Dash_File}.delete");
    Debug.WriteLine("Removed Old Dash File");
}

Before attempting to move so should prevent the file being left behind and causing this issue from happening again.
